@id = 00000000-0000-0000-0000-000000000000

PUT http://localhost:5017/items/{{id}}
Content-Type: application/json

{
    "name": "Chest radiography",
    "description": "X-ray radiography that goes from the base of the...",
    "price": 2316.33
}